services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "3000:3000"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
