services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    volumes:
      - .:/var/www
      - /var/www/vendor
      - ./database/database.sqlite:/var/www/database/database.sqlite
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "3000:3000"

networks:
  app-network:
