# Dockerfile.frontend

# Utiliser une image de base pour Node.js
FROM node:20

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'application
COPY . .

# Construire l'application pour la production
# RUN npm run build

RUN rm -rf node_modules
RUN rm -rf package-lock.json

RUN npm install

# Exposer le port 3000
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["npm", "run", "dev"]
